spring.application.name=titu
# Configuração do Banco de Dados (Docker)
spring.datasource.url=jdbc:postgresql://localhost:5432/titu_db
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuração do JPA (Pra ele criar as tabelas sozinho)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# --- Configuração de E-mail (Mailtrap) ---
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=05743ef0418e50
spring.mail.password=134ebab52d77b0
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true